project:
  type: website
  render:
    - "*.ipynb"

format:
  html:
    toc: true
    toc-depth: 5
    css: styles.css
    page-layout: full
    code-block-bg: true
    code-overflow: wrap
    code-line-numbers: false
    monofont: D2Coding
    language:
      crossref-tbl-title: "표"
    mermaid:
      theme: neutral

website:
  title: "Blender Book"
  sidebar:
    style: "docked"
    search: true
    contents:
      - "index.ipynb"
      - section: "블렌더"
        contents:
        - "intro.ipynb"
        - "start.ipynb"
      - section: "인터페이스"
        contents:
        - "interface.ipynb"
        - "3dviewport.ipynb"
        - "viewpoint.ipynb"
        - "outliner.ipynb"
        - "select.ipynb"
        - "properties.ipynb"
        - "scene.ipynb"
      - section: "3D 모델링"
        contents:
        - "3d_intro.ipynb"
        - "transform.ipynb"
        - "add.ipynb"
      - section: "2D 애니메이션"
        contents:
        - "2d_intro.ipynb"
